### PR TITLE
Minor documentation fixes

### PR DESCRIPTION
**Pull request by mk-fg**
As a random extra note: I think including a reference to examples (you have these in "test" dir) at the start of C/C++ API docs would be prehaps more useful than the description itself.

### CODE REVIEW

**Comment by LucaFulchir** [comment]
The tests were created after the documentation, but it's a good point, I'll add something.

The project however requires a [CLA](https://www.fenrirproject.org/Fenrir/Fenrir_Project/wikis/CLA) to be signed, as it will become part of a bigger project (but will remain LGPL3 and freely usable standalone, don't worry)
So I can't accept the pull requests for now, sorry.

Sometime in January the project will start receiving new features and API changes, so tests and documentations will change accordingly.

**Comment by mk-fg** [comment]
Won't it work for me to explicitly grant you permission to use all the changes in this PR under any license from here on and until teh Heat Death of Universe, right here and now?

**Comment by LucaFulchir** [comment]
That's about what the [CLA](https://www.fenrirproject.org/Fenrir/Fenrir_Project/wikis/CLA) does, except you still retain some rights (non-exclusivity, code reuse...).
"here and now" sound really nice, but as far as I understand it has no legal value :(

...That's why CLAs are a pain for open source projects, but there are some incompatibilities between lgpl and -for example- apple/windows stores, plus I don't really mind static linking, so double-licensing is really the only way to overcome these problems for now

**Comment by mk-fg** [comment]
Oh well, pity.
Thanks for the explaination.

Don't see why'd such statement have less value than e.g. copyright claim to same code by same github account at the same time in the first place, but guess laws can be weirder than quantum mechanics to the uninitiated.

Cheers!

**Comment by mk-fg** [comment]
Guess I'll close the PRs, as you can't accept these and noted all the changes anyway.

Btw, I did make a python wrapper and cli tool for the lib yesterday - https://github.com/mk-fg/python-libraptorq ([on PyPI as well](https://pypi.python.org/pypi/libraptorq)), which might be useful to experiment with the algo in pseudocode.

**Pull request closed without merging**
